/**
 * AI Report Builder - PDF Generator
 *
 * Production-grade PDF generation for AI-analyzed claims.
 * Creates branded, professional reports ready for homeowners,
 * adjusters, and carriers.
 */

import PDFDocument from "pdfkit";

import type { StormIntakeResults } from "@/lib/ai/pipelines/stormIntake";

export interface ReportData {
  claimId: string;
  claimNumber?: string;
  property: {
    address: string;
    city: string;
    state: string;
    zip: string;
  };
  analysis: StormIntakeResults;
  generatedAt: string;
  generatedBy: string;
  orgName?: string;
}

export async function generatePDFBuffer(reportData: ReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: 50,
        size: "LETTER",
        info: {
          Title: `SkaiScraper AI Report - ${reportData.claimId}`,
          Author: "SkaiScraper AI Platform",
          Subject: "Storm Damage Analysis Report",
          Creator: "SkaiScraper",
        },
      });

      const buffers: Buffer[] = [];
      doc.on("data", buffers.push.bind(buffers));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", reject);

      // HEADER
      doc.fontSize(28).fillColor("#2563eb").text("SkaiScraper AI Report", { align: "center" });

      doc
        .fontSize(12)
        .fillColor("#64748b")
        .text("Powered by Advanced Machine Learning", { align: "center" });

      doc.moveDown(2);

      // CLAIM INFORMATION
      doc.fontSize(10).fillColor("#000000");
      doc.text(`Claim ID: ${reportData.claimId}`, { continued: false });
      if (reportData.claimNumber) {
        doc.text(`Claim Number: ${reportData.claimNumber}`);
      }
      doc.text(`Generated: ${new Date(reportData.generatedAt).toLocaleString()}`);
      doc.text(`Generated By: ${reportData.generatedBy}`);
      if (reportData.orgName) {
        doc.text(`Organization: ${reportData.orgName}`);
      }

      doc.moveDown();
      doc.strokeColor("#e2e8f0").lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown();

      // PROPERTY INFORMATION
      doc.fontSize(18).fillColor("#1e293b").text("🏠 Property Information");
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor("#000000");
      doc.text(reportData.property.address);
      doc.text(
        `${reportData.property.city}, ${reportData.property.state} ${reportData.property.zip}`
      );
      doc.moveDown(1.5);

      // EXECUTIVE SUMMARY
      doc.fontSize(18).fillColor("#1e293b").text("📊 Executive Summary");
      doc.moveDown(0.5);

      const summary = reportData.analysis.summary;
      doc.fontSize(11).fillColor("#000000");
      doc.text(`Total Images Analyzed: ${summary.totalImages}`);
      doc.text(`Damage Detected: ${summary.damageDetected ? "YES" : "NO"}`);
      doc.text(`Primary Damage Type: ${summary.primaryDamageType.toUpperCase()}`);
      doc.text(`AI Confidence Score: ${(summary.confidenceScore * 100).toFixed(1)}%`);
      doc.text(`Overall Severity: ${summary.overallSeverity.toUpperCase()}`);
      doc.moveDown(1.5);

      // SEVERITY INDICATOR BOX
      const severityColors = {
        minor: "#10b981",
        moderate: "#f59e0b",
        severe: "#ef4444",
        catastrophic: "#7f1d1d",
      };
      const severityColor = severityColors[summary.overallSeverity];

      doc.rect(50, doc.y, 500, 40).fillAndStroke(severityColor, severityColor);
      doc.fontSize(16).fillColor("#ffffff");
      doc.text(`SEVERITY: ${summary.overallSeverity.toUpperCase()}`, 50, doc.y - 30, {
        width: 500,
        align: "center",
      });
      doc.moveDown(2);

      // DAMAGE ANALYSIS
      doc.fontSize(18).fillColor("#1e293b").text("🔍 Detailed Damage Analysis");
      doc.moveDown(0.5);

      const damage = reportData.analysis.damageAnalysis;

      // Hail Damage
      if (damage.hailDamage.detected) {
        doc.fontSize(14).fillColor("#2563eb").text("Hail Damage");
        doc.moveDown(0.3);
        doc.fontSize(11).fillColor("#000000");
        doc.text(`Affected Areas: ${damage.hailDamage.affectedAreas.join(", ")}`);
        doc.text(`Estimated Impact Count: ${damage.hailDamage.impactCount}`);
        doc.text(`Average Hail Size: ${damage.hailDamage.averageSize}`);
        doc.text(`Detection Confidence: ${(damage.hailDamage.confidence * 100).toFixed(1)}%`);
        doc.moveDown(1);
      }

      // Wind Damage
      if (damage.windDamage.detected) {
        doc.fontSize(14).fillColor("#2563eb").text("Wind Damage");
        doc.moveDown(0.3);
        doc.fontSize(11).fillColor("#000000");
        doc.text(`Affected Areas: ${damage.windDamage.affectedAreas.join(", ")}`);
        doc.text(`Missing Shingles: ${damage.windDamage.missingShingles ? "YES" : "NO"}`);
        doc.text(`Lifted Shingles: ${damage.windDamage.liftedShingles ? "YES" : "NO"}`);
        doc.text(`Detection Confidence: ${(damage.windDamage.confidence * 100).toFixed(1)}%`);
        doc.moveDown(1);
      }

      // Structural Issues
      if (damage.structuralIssues.detected) {
        doc.fontSize(14).fillColor("#dc2626").text("⚠️ Structural Issues");
        doc.moveDown(0.3);
        doc.fontSize(11).fillColor("#000000");
        doc.text(`Urgency Level: ${damage.structuralIssues.urgency.toUpperCase()}`);
        damage.structuralIssues.issues.forEach((issue) => {
          doc.text(`  • ${issue}`);
        });
        doc.moveDown(1);
      }

      doc.moveDown(1);

      // ROOF METRICS
      doc.fontSize(18).fillColor("#1e293b").text("📐 Roof Metrics");
      doc.moveDown(0.5);

      const metrics = reportData.analysis.roofMetrics;
      doc.fontSize(11).fillColor("#000000");
      doc.text(
        `Estimated Area: ${metrics.estimatedArea} sq ft (${Math.ceil(metrics.estimatedArea / 100)} squares)`
      );
      doc.text(`Roof Pitch: ${metrics.pitch}:12`);
      doc.text(`Number of Slopes: ${metrics.slopes}`);
      doc.text(`Roofing Material: ${metrics.material}`);
      doc.text(`Estimated Age: ${metrics.age}`);
      doc.text(`Current Condition: ${metrics.condition}`);
      doc.moveDown(1.5);

      // RECOMMENDATIONS
      doc.fontSize(18).fillColor("#1e293b").text("💡 AI Recommendations");
      doc.moveDown(0.5);

      const recs = reportData.analysis.recommendations;

      doc.fontSize(14).fillColor("#dc2626").text("Immediate Actions");
      doc.moveDown(0.3);
      doc.fontSize(11).fillColor("#000000");
      recs.immediateActions.forEach((action, idx) => {
        doc.text(`${idx + 1}. ${action}`);
      });
      doc.moveDown(1);

      doc.fontSize(14).fillColor("#2563eb").text("Repair Scope");
      doc.moveDown(0.3);
      doc.fontSize(11).fillColor("#000000");
      recs.repairScope.forEach((item, idx) => {
        doc.text(`${idx + 1}. ${item}`);
      });
      doc.moveDown(1);

      doc.fontSize(14).fillColor("#16a34a").text("Cost Estimate");
      doc.moveDown(0.3);
      doc.fontSize(11).fillColor("#000000");
      doc.text(`Low Estimate: $${recs.estimatedCost.low.toLocaleString()}`);
      doc.text(`Recommended: $${recs.estimatedCost.recommended.toLocaleString()}`);
      doc.text(`High Estimate: $${recs.estimatedCost.high.toLocaleString()}`);
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor("#64748b");
      doc.text("*Estimates are preliminary and subject to on-site verification");
      doc.moveDown(1);

      doc.fontSize(14).fillColor("#7c3aed").text("Recommended Timeline");
      doc.moveDown(0.3);
      doc.fontSize(11).fillColor("#000000");
      doc.text(recs.timeline);
      doc.moveDown(2);

      // IMAGE ANALYSIS SUMMARY
      if (reportData.analysis.captionedImages.length > 0) {
        doc.addPage();
        doc.fontSize(18).fillColor("#1e293b").text("📸 Image Analysis Summary");
        doc.moveDown(1);

        reportData.analysis.captionedImages.forEach((img, idx) => {
          doc
            .fontSize(12)
            .fillColor("#2563eb")
            .text(`Image ${idx + 1}`);
          doc.fontSize(10).fillColor("#000000");
          doc.text(`Damage Type: ${img.damageType}`);
          doc.text(`Severity: ${img.severity}`);
          doc.text(`Confidence: ${(img.confidence * 100).toFixed(1)}%`);
          doc.fontSize(10).fillColor("#475569");
          doc.text(`Caption: ${img.caption}`);
          doc.moveDown(1);

          // Add spacing
          if ((idx + 1) % 3 === 0 && idx < reportData.analysis.captionedImages.length - 1) {
            doc.moveDown(1);
          }
        });
      }

      // FOOTER
      doc.addPage();
      doc.fontSize(16).fillColor("#1e293b").text("Important Notes", { align: "center" });
      doc.moveDown(1);
      doc.fontSize(10).fillColor("#475569");
      doc.text(
        "This report was generated by SkaiScraper's advanced AI platform using computer vision, machine learning, and predictive analytics. All damage assessments and cost estimates are preliminary and should be verified by a licensed roofing professional.",
        { align: "left" }
      );
      doc.moveDown(1);
      doc.text(
        "The AI confidence scores represent the system's certainty in its analysis based on available image data. Higher confidence scores indicate more reliable predictions.",
        { align: "left" }
      );
      doc.moveDown(1);
      doc.text(
        "This report does not constitute a professional inspection or warranty. Always consult with licensed contractors and insurance adjusters before making repair decisions.",
        { align: "left" }
      );

      doc.moveDown(3);
      doc.fontSize(12).fillColor("#2563eb").text("SkaiScraper AI Platform", { align: "center" });
      doc.fontSize(10).fillColor("#64748b").text("Advanced Insurance Claims Intelligence", {
        align: "center",
      });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
