"use client";

import { AnimatePresence, motion } from "framer-motion";
import {
  Brain,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  FileText,
  Loader2,
  MapPin,
  Play,
  RotateCcw,
  Sparkles,
} from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";

/* ------------------------------------------------------------------ */
/*  Mock data                                                          */
/* ------------------------------------------------------------------ */

const SAMPLE_INPUTS = {
  address: "4821 N Thunderbird Way, Flagstaff, AZ 86004",
  roofType: "Architectural Shingle — CertainTeed Landmark Pro",
  stormDate: "January 15, 2026",
  squares: "32.4",
  slope: "6/12 hip-and-valley",
};

const NARRATIVE_SECTIONS = [
  {
    label: "Header",
    lines: [
      "PROPERTY DAMAGE ASSESSMENT REPORT",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "",
      `Property: ${SAMPLE_INPUTS.address}`,
      `Date of Loss: ${SAMPLE_INPUTS.stormDate}`,
      "Inspector: Field Tech — SkaiScraper AI Engine v3.2",
      "",
    ],
  },
  {
    label: "Roof System",
    lines: [
      "ROOF SYSTEM ANALYSIS",
      "────────────────────",
      `System: ${SAMPLE_INPUTS.roofType}`,
      `Roof Age: 8 years  |  Squares: ${SAMPLE_INPUTS.squares}`,
      `Slope: ${SAMPLE_INPUTS.slope} configuration`,
      "",
    ],
  },
  {
    label: "Storm Verification",
    lines: [
      "STORM DAMAGE FINDINGS",
      "────────────────────",
      "Hail Impact: Confirmed — 1.25″ diameter verified via NOAA radar",
      "Wind Speed: Sustained 58 mph / Gusts 72 mph recorded at 14:32 MST",
      "",
      "Damage observed on all four slopes with concentrated impact",
      "zones on south and west exposures. Soft metal test points on",
      "ridge vents, pipe boots, and drip edge confirm hail impact",
      "trajectory consistent with recorded storm path.",
      "",
    ],
  },
  {
    label: "Damage Detail",
    lines: [
      "SHINGLE DAMAGE DETAIL",
      "────────────────────",
      "✓  47 impact marks per 10×10 test square",
      "✓  Granule displacement — exposed fiberglass mat",
      "✓  Fracturing along bond line on south slope",
      "✓  Bruising confirmed via tactile on north slope",
      "✓  Ridge caps: splits at 60% of test points",
      "",
    ],
  },
  {
    label: "Collateral",
    lines: [
      "COLLATERAL DAMAGE",
      "────────────────────",
      "• Gutters — 18 impact marks per 10 LF (south-facing)",
      "• Window screens — 3 screens with perforation damage",
      "• Fence — 12 pickets with hail scarring (west privacy)",
      "• HVAC condenser — top grille impact dimpling",
      "",
    ],
  },
  {
    label: "Recommendation",
    lines: [
      "RECOMMENDATION",
      "────────────────────",
      "Full roof system replacement recommended. Damage exceeds",
      "repair threshold per manufacturer warranty guidelines.",
      "",
      "Estimated RCV:     $28,470.00",
      "Depreciation:       $4,840.00",
      "ACV:               $23,630.00",
      "",
      "— Generated by SkaiScraper AI Engine v3.2",
    ],
  },
];

const FULL_TEXT = NARRATIVE_SECTIONS.flatMap((s) => s.lines).join("\n");

/* ------------------------------------------------------------------ */
/*  Processing steps (fake pipeline)                                   */
/* ------------------------------------------------------------------ */

const PIPELINE_STEPS = [
  "Verifying storm data against NOAA records…",
  "Analyzing roof system specifications…",
  "Cross-referencing hail trajectory models…",
  "Calculating damage density per test square…",
  "Identifying collateral damage patterns…",
  "Assembling proposal-ready narrative…",
];

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

type DemoState = "idle" | "processing" | "typing" | "done";

export function AIDamageBuilderDemo() {
  const [state, setState] = useState<DemoState>("idle");
  const [pipelineStep, setPipelineStep] = useState(0);
  const [displayedText, setDisplayedText] = useState("");
  const [currentSection, setCurrentSection] = useState(0);
  const [expanded, setExpanded] = useState(false);
  const textRef = useRef<HTMLDivElement>(null);
  const charIndex = useRef(0);

  /* Auto-scroll the output pane */
  useEffect(() => {
    if (textRef.current) {
      textRef.current.scrollTop = textRef.current.scrollHeight;
    }
  }, [displayedText]);

  /* Pipeline animation */
  useEffect(() => {
    if (state !== "processing") return;
    if (pipelineStep >= PIPELINE_STEPS.length) {
      setState("typing");
      return;
    }
    const t = setTimeout(() => setPipelineStep((p) => p + 1), 600);
    return () => clearTimeout(t);
  }, [state, pipelineStep]);

  /* Typewriter effect */
  useEffect(() => {
    if (state !== "typing") return;
    if (charIndex.current >= FULL_TEXT.length) {
      setState("done");
      return;
    }
    const speed = FULL_TEXT[charIndex.current] === "\n" ? 12 : 8;
    const t = setTimeout(() => {
      charIndex.current += 1;
      setDisplayedText(FULL_TEXT.slice(0, charIndex.current));

      // Track which section we're in
      let count = 0;
      for (let i = 0; i < NARRATIVE_SECTIONS.length; i++) {
        count += NARRATIVE_SECTIONS[i].lines.join("\n").length + 1;
        if (charIndex.current < count) {
          setCurrentSection(i);
          break;
        }
      }
    }, speed);
    return () => clearTimeout(t);
  }, [state, displayedText]);

  const handleStart = useCallback(() => {
    setState("processing");
    setPipelineStep(0);
    setDisplayedText("");
    setCurrentSection(0);
    charIndex.current = 0;
  }, []);

  const handleReset = useCallback(() => {
    setState("idle");
    setPipelineStep(0);
    setDisplayedText("");
    setCurrentSection(0);
    charIndex.current = 0;
  }, []);

  return (
    <div className="overflow-hidden rounded-3xl border border-border bg-card shadow-2xl">
      {/* Header bar */}
      <div className="flex items-center justify-between border-b border-border bg-gradient-to-r from-slate-50 to-slate-100 px-6 py-4 dark:from-slate-800/80 dark:to-slate-800/50">
        <div className="flex items-center gap-3">
          <div className="rounded-xl bg-gradient-to-br from-blue-500 to-blue-600 p-2.5">
            <Brain className="h-5 w-5 text-white" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-foreground">AI Damage Builder</h3>
            <p className="text-xs text-muted-foreground">Live Demo — No account required</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {state === "done" && (
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              className="flex items-center gap-1 rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-semibold text-emerald-600 dark:text-emerald-400"
            >
              <CheckCircle2 className="h-3.5 w-3.5" />
              Complete
            </motion.div>
          )}
          {state === "typing" && (
            <div className="flex items-center gap-1 rounded-full bg-blue-500/10 px-3 py-1 text-xs font-semibold text-blue-600 dark:text-blue-400">
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
              Generating…
            </div>
          )}
        </div>
      </div>

      <div className="flex flex-col lg:flex-row">
        {/* Left — Input Panel */}
        <div className="border-b border-border p-6 lg:w-80 lg:shrink-0 lg:border-b-0 lg:border-r">
          <p className="mb-4 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
            Sample Claim Input
          </p>

          <div className="space-y-3">
            <InputField icon={MapPin} label="Property" value={SAMPLE_INPUTS.address} />
            <InputField icon={FileText} label="Roof System" value={SAMPLE_INPUTS.roofType} />
            <InputField icon={FileText} label="Storm Date" value={SAMPLE_INPUTS.stormDate} />
            <div className="flex gap-3">
              <InputField icon={FileText} label="Squares" value={SAMPLE_INPUTS.squares} small />
              <InputField icon={FileText} label="Slope" value={SAMPLE_INPUTS.slope} small />
            </div>
          </div>

          {/* Action button */}
          <div className="mt-6">
            {state === "idle" ? (
              <button
                onClick={handleStart}
                className="group flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#117CFF] to-[#004AAD] px-6 py-3 text-sm font-bold text-white shadow-lg transition-all hover:scale-[1.02] hover:shadow-xl active:scale-[0.98]"
              >
                <Play className="h-4 w-4 transition-transform group-hover:scale-110" />
                Generate AI Narrative
              </button>
            ) : (
              <button
                onClick={handleReset}
                className="flex w-full items-center justify-center gap-2 rounded-xl border border-border px-6 py-3 text-sm font-semibold text-muted-foreground transition-colors hover:bg-muted"
              >
                <RotateCcw className="h-4 w-4" />
                Reset Demo
              </button>
            )}
          </div>

          {/* Section progress */}
          <AnimatePresence>
            {(state === "typing" || state === "done") && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: "auto" }}
                exit={{ opacity: 0, height: 0 }}
                className="mt-6 overflow-hidden"
              >
                <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Sections
                </p>
                <div className="space-y-1">
                  {NARRATIVE_SECTIONS.map((section, i) => (
                    <div
                      key={section.label}
                      className={`flex items-center gap-2 rounded-lg px-2 py-1.5 text-xs transition-all ${
                        i < currentSection || state === "done"
                          ? "text-emerald-600 dark:text-emerald-400"
                          : i === currentSection && state === "typing"
                            ? "font-semibold text-[#117CFF]"
                            : "text-muted-foreground"
                      }`}
                    >
                      {i < currentSection || state === "done" ? (
                        <CheckCircle2 className="h-3.5 w-3.5 shrink-0" />
                      ) : i === currentSection && state === "typing" ? (
                        <Loader2 className="h-3.5 w-3.5 shrink-0 animate-spin" />
                      ) : (
                        <span className="h-3.5 w-3.5 shrink-0 rounded-full border border-muted-foreground/30" />
                      )}
                      {section.label}
                    </div>
                  ))}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* Right — Output Panel */}
        <div className="flex-1 p-6">
          {state === "idle" && (
            <div className="flex h-72 flex-col items-center justify-center text-center lg:h-96">
              <div className="mb-4 rounded-2xl bg-gradient-to-br from-[#117CFF]/10 to-[#004AAD]/10 p-6">
                <Sparkles className="h-10 w-10 text-[#117CFF]" />
              </div>
              <p className="text-lg font-semibold text-foreground">See the AI in action</p>
              <p className="mt-1 max-w-xs text-sm text-muted-foreground">
                Click &quot;Generate AI Narrative&quot; to watch SkaiScraper build a real damage
                assessment in real-time.
              </p>
            </div>
          )}

          {state === "processing" && (
            <div className="flex h-72 flex-col items-center justify-center lg:h-96">
              <Loader2 className="mb-6 h-10 w-10 animate-spin text-[#117CFF]" />
              <div className="w-full max-w-xs space-y-2">
                {PIPELINE_STEPS.map((step, i) => (
                  <motion.div
                    key={step}
                    initial={{ opacity: 0, x: -10 }}
                    animate={i <= pipelineStep ? { opacity: 1, x: 0 } : { opacity: 0.3, x: -10 }}
                    transition={{ duration: 0.3 }}
                    className="flex items-center gap-2 text-sm"
                  >
                    {i < pipelineStep ? (
                      <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-500" />
                    ) : i === pipelineStep ? (
                      <Loader2 className="h-4 w-4 shrink-0 animate-spin text-[#117CFF]" />
                    ) : (
                      <span className="h-4 w-4 shrink-0 rounded-full border border-muted-foreground/30" />
                    )}
                    <span
                      className={
                        i < pipelineStep
                          ? "text-emerald-600 dark:text-emerald-400"
                          : i === pipelineStep
                            ? "font-medium text-foreground"
                            : "text-muted-foreground"
                      }
                    >
                      {step}
                    </span>
                  </motion.div>
                ))}
              </div>
            </div>
          )}

          {(state === "typing" || state === "done") && (
            <div className="relative">
              {/* Professional PDF-style output */}
              <div
                className={`overflow-y-auto rounded-xl border border-slate-200 bg-white shadow-lg transition-all dark:border-slate-700 dark:bg-slate-50 ${
                  expanded ? "max-h-[600px]" : "max-h-72 lg:max-h-96"
                }`}
              >
                {/* PDF Header Bar */}
                <div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-200 bg-gradient-to-r from-slate-50 to-slate-100 px-5 py-2.5">
                  <div className="flex items-center gap-2">
                    <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-gradient-to-br from-blue-500 to-blue-600">
                      <FileText className="h-3.5 w-3.5 text-white" />
                    </div>
                    <div>
                      <p className="text-[11px] font-bold text-slate-800">
                        Property Damage Assessment
                      </p>
                      <p className="text-[9px] text-slate-500">SkaiScraper AI Engine v3.2</p>
                    </div>
                  </div>
                  <span className="rounded-full bg-emerald-100 px-2 py-0.5 text-[9px] font-bold text-emerald-700">
                    PDF READY
                  </span>
                </div>

                {/* PDF Content */}
                <div className="p-5 font-sans text-[12px] leading-relaxed text-slate-800">
                  {displayedText.split("\n").map((line, i) => {
                    if (
                      line.startsWith("PROPERTY DAMAGE") ||
                      line.startsWith("ROOF SYSTEM") ||
                      line.startsWith("STORM DAMAGE") ||
                      line.startsWith("SHINGLE DAMAGE") ||
                      line.startsWith("COLLATERAL") ||
                      line.startsWith("RECOMMENDATION")
                    ) {
                      return (
                        <h3
                          key={i}
                          className="mb-1 mt-4 text-[13px] font-bold tracking-wide text-blue-900 first:mt-0"
                        >
                          {line}
                        </h3>
                      );
                    }
                    if (line.startsWith("━") || line.startsWith("─")) {
                      return <hr key={i} className="my-1.5 border-blue-200" />;
                    }
                    if (line.startsWith("✓")) {
                      return (
                        <p key={i} className="flex items-start gap-1.5 py-0.5 text-emerald-700">
                          <CheckCircle2 className="mt-0.5 h-3 w-3 shrink-0" />
                          <span>{line.slice(2).trim()}</span>
                        </p>
                      );
                    }
                    if (line.startsWith("•")) {
                      return (
                        <p key={i} className="py-0.5 pl-3 text-slate-700">
                          {line}
                        </p>
                      );
                    }
                    if (
                      line.startsWith("Estimated RCV") ||
                      line.startsWith("Depreciation") ||
                      line.startsWith("ACV")
                    ) {
                      return (
                        <p key={i} className="font-semibold text-slate-900">
                          {line}
                        </p>
                      );
                    }
                    if (line.startsWith("— Generated")) {
                      return (
                        <p
                          key={i}
                          className="mt-3 border-t border-slate-200 pt-2 text-[10px] italic text-slate-400"
                        >
                          {line}
                        </p>
                      );
                    }
                    if (line.trim() === "") return <div key={i} className="h-2" />;
                    return (
                      <p key={i} className="text-slate-700">
                        {line}
                      </p>
                    );
                  })}
                  {state === "typing" && (
                    <span className="inline-block h-4 w-0.5 animate-pulse bg-blue-500" />
                  )}
                </div>
              </div>

              {state === "done" && (
                <div className="mt-3 flex items-center justify-between">
                  <button
                    onClick={() => setExpanded(!expanded)}
                    className="flex items-center gap-1 text-xs font-medium text-muted-foreground transition-colors hover:text-foreground"
                  >
                    {expanded ? (
                      <>
                        <ChevronUp className="h-3.5 w-3.5" /> Collapse
                      </>
                    ) : (
                      <>
                        <ChevronDown className="h-3.5 w-3.5" /> Expand full report
                      </>
                    )}
                  </button>
                  <div className="flex items-center gap-4 text-xs text-muted-foreground">
                    <span>
                      <strong className="text-foreground">6</strong> sections
                    </span>
                    <span>
                      <strong className="text-foreground">2.4s</strong> generation time
                    </span>
                    <span>
                      <strong className="text-foreground">PDF ready</strong>
                    </span>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  Sub-components                                                     */
/* ------------------------------------------------------------------ */

function InputField({
  icon: Icon,
  label,
  value,
  small,
}: {
  icon: typeof MapPin;
  label: string;
  value: string;
  small?: boolean;
}) {
  return (
    <div className={small ? "flex-1" : ""}>
      <label className="mb-1 block text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
        {label}
      </label>
      <div className="flex items-center gap-2 rounded-lg border border-border bg-muted/50 px-3 py-2">
        <Icon className="h-3.5 w-3.5 shrink-0 text-muted-foreground" />
        <span className="truncate text-xs text-foreground">{value}</span>
      </div>
    </div>
  );
}
