// ============================================================================
// REPORT BUILDER TYPES — CompanyCam-Inspired Project Management
// ============================================================================
// Phase 2: Full project management with photos, reports, estimates, docs
// ============================================================================

export interface Project {
  id: string;
  organizationId: string;
  createdById: string;
  createdAt: Date;
  updatedAt: Date;

  // Property Info
  propertyAddress: string;
  insured_name: string;
  latitude?: number;
  longitude?: number;

  // Project Meta
  status: "active" | "archived" | "completed";
  labels: string[]; // ["hail", "commercial", "urgent", etc.]
  
  // Stats
  photoCount: number;
  reportCount: number;
  estimateCount: number;
}

export interface Photo {
  id: string;
  projectId: string;
  uploadedById: string;
  uploadedAt: Date;

  // Storage
  url: string;
  thumbnailUrl?: string;
  fileName: string;
  fileSize: number;
  mimeType: string;

  // AI Metadata
  aiCaption?: string;
  aiDamageType?: string[]; // ["hail", "wind", "soft-metal-dents"]
  aiConfidence?: number;
  aiLabels?: string[];

  // Manual Metadata
  caption?: string;
  tags: string[];
  roofArea?: "front" | "back" | "left" | "right" | "skylight" | "vent" | "flashing" | "interior";
  sortOrder: number;

  // Status
  isDeleted: boolean;
  deletedAt?: Date;
}

export interface Report {
  id: string;
  projectId: string;
  createdById: string;
  createdAt: Date;
  updatedAt: Date;

  // Report Type
  type: "insurance-claim" | "retail-proposal" | "inspection" | "supplement" | "code-compliance";
  version: "insurance" | "retail";
  
  // Content
  title: string;
  status: "draft" | "final" | "sent";
  
  // Data (from ClaimPacketData)
  data: Record<string, any>; // Flexible JSON storage for claim packet data
  
  // Export History
  lastExportedAt?: Date;
  lastExportFormat?: "pdf" | "docx";
  
  // Sections (drag/reorder)
  sections: ReportSection[];
}

export interface ReportSection {
  id: string;
  reportId: string;
  
  // Section Type
  type: 
    | "cover-page" 
    | "weather" 
    | "damage-summary" 
    | "photos" 
    | "scope" 
    | "code-references" 
    | "contractor-letter" 
    | "supplement"
    | "timeline"
    | "material-options"
    | "warranty"
    | "signature";
  
  // Content
  title: string;
  content: string; // Markdown or JSON
  isVisible: boolean;
  sortOrder: number;
  
  // Auto-Generated Flag
  isAutoGenerated: boolean;
  lastAIGeneratedAt?: Date;
}

export interface Estimate {
  id: string;
  projectId: string;
  createdById: string;
  createdAt: Date;
  updatedAt: Date;

  // Estimate Type
  type: "xactimate" | "manual" | "ai-generated";
  
  // Content
  title: string;
  status: "draft" | "final" | "approved";
  
  // Line Items (simplified)
  lineItems: EstimateLineItem[];
  totalAmount: number;
  
  // Export
  xactimateXML?: string;
  lastExportedAt?: Date;
}

export interface EstimateLineItem {
  id: string;
  estimateId: string;
  
  // Item Details
  code?: string; // Xactimate code
  description: string;
  quantity: number;
  unit: string;
  unitPrice: number;
  totalPrice: number;
  
  // Category
  category: "roofing" | "siding" | "interior" | "other";
  sortOrder: number;
}

export interface Document {
  id: string;
  projectId: string;
  uploadedById: string;
  uploadedAt: Date;

  // Storage
  url: string;
  fileName: string;
  fileSize: number;
  mimeType: string;
  
  // Metadata
  type: "contract" | "permit" | "invoice" | "correspondence" | "other";
  tags: string[];
  
  // Status
  isDeleted: boolean;
  deletedAt?: Date;
}

export interface Contact {
  id: string;
  projectId: string;
  
  // Contact Info
  name: string;
  email?: string;
  phone?: string;
  company?: string;
  
  // Role
  role: "homeowner" | "adjuster" | "contractor" | "agent" | "other";
  
  // Metadata
  notes?: string;
}

// ============================================================================
// AI ACTION TYPES
// ============================================================================

export interface AIAction {
  type: 
    | "auto-caption-photos"
    | "detect-damage-types"
    | "generate-full-report"
    | "build-scope-from-photos"
    | "fetch-weather-data"
    | "extract-code-references";
  
  projectId: string;
  triggeredById: string;
  triggeredAt: Date;
  
  status: "pending" | "running" | "completed" | "failed";
  
  // Results
  result?: any;
  error?: string;
}

// ============================================================================
// UI COMPONENT PROPS
// ============================================================================

export interface SidebarNavProps {
  projectId: string;
  activeTab: "photos" | "reports" | "estimates" | "docs" | "contacts" | "settings";
}

export interface SectionListProps {
  reportId: string;
  sections: ReportSection[];
  onReorder: (sections: ReportSection[]) => void;
  onToggleVisibility: (sectionId: string) => void;
  onDelete: (sectionId: string) => void;
}

export interface SectionEditorProps {
  section: ReportSection;
  onChange: (section: ReportSection) => void;
}

export interface PhotoTrayProps {
  projectId: string;
  photos: Photo[];
  onUpload: (files: File[]) => void;
  onDelete: (photoId: string) => void;
  onUpdateCaption: (photoId: string, caption: string) => void;
}

export interface AIActionsBarProps {
  projectId: string;
  onGenerateReport: () => void;
  onAutoCaptionPhotos: () => void;
  onBuildScope: () => void;
  onFetchWeather: () => void;
}
