// src/app/(app)/exports/supplements/[supplementId]/packet/page.tsx
import { auth } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";

import { buildSupplementPacketPayload } from "@/lib/export/payloads";

type PageProps = { params: { supplementId: string } };

export default async function SupplementPacketPage({ params }: PageProps) {
  const { userId, orgId } = await auth();
  if (!userId) redirect("/sign-in");

  const supplementId = params.supplementId;

  const payload = await buildSupplementPacketPayload(supplementId, orgId ?? null);
  const {
    claim,
    supplements: supplement,
    lineItems,
    subtotal,
    taxRate,
    taxAmount,
    opEnabled,
    opPercent,
    opAmount,
    grandTotal,
  } = payload;

  const claimNumber = claim?.claimNumber ?? claim?.id?.slice(0, 8) ?? "Standalone";

  const scopeData = (supplement.scopeItems as any) ?? {};
  const notes = supplement.notes ?? scopeData.notesToAdjuster ?? "";
  const carrierContext = scopeData.carrierEstimateSummary ?? "";
  const codeCitations = Array.isArray(scopeData.codeCitations) ? scopeData.codeCitations : [];

  return (
    <div className="mx-auto max-w-5xl space-y-6 bg-white p-8 text-black print:p-4">
      {/* Header */}
      <header className="space-y-1 border-b pb-4">
        <h1 className="text-2xl font-bold">
          {supplement.id ? "Supplement Packet" : "Supplement Packet"}
        </h1>
        <p className="text-sm">
          Claim: <strong>{claimNumber}</strong>
        </p>
        {claim && (
          <>
            <p className="text-sm">Insured: {claim.insured_name ?? "—"}</p>
            <p className="text-sm">
              Property: {claim.propertyAddress ?? claim.properties?.address ?? "—"}
            </p>
            <p className="text-sm">Carrier: {claim.carrier ?? "—"}</p>
            <p className="text-sm">
              Date of Loss:{" "}
              {claim.dateOfLoss ? new Date(claim.dateOfLoss).toLocaleDateString() : "—"}
            </p>
          </>
        )}
        <p className="text-xs text-gray-600">
          Generated by SkaiScraper – Supplement request packet
        </p>
      </header>

      {/* Context / Narrative */}
      <section className="space-y-2 text-sm">
        <h2 className="border-b pb-1 text-lg font-semibold">Supplement Context</h2>
        {carrierContext && (
          <p className="whitespace-pre-wrap text-xs text-gray-700">{carrierContext}</p>
        )}
        <p className="whitespace-pre-wrap">
          {notes ||
            "We are requesting the following additional items to bring the scope in line with code and manufacturer requirements, and to restore the property to its pre-loss condition."}
        </p>
      </section>

      {/* Code Citations (if any) */}
      {codeCitations.length > 0 && (
        <section className="space-y-2 text-sm">
          <h2 className="border-b pb-1 text-lg font-semibold">Code &amp; Manufacturer Support</h2>
          <ul className="list-inside list-disc space-y-1">
            {codeCitations.map((c: any, idx: number) => (
              <li key={idx}>
                {c.code ? <strong>{c.code}: </strong> : null}
                {c.text ?? ""}
              </li>
            ))}
          </ul>
        </section>
      )}

      {/* Line Items */}
      <section className="space-y-2 text-sm">
        <h2 className="border-b pb-1 text-lg font-semibold">Requested Supplement Items</h2>
        <table className="w-full border-collapse text-[11px]">
          <thead>
            <tr className="bg-gray-100">
              <th className="border px-2 py-1 text-left">#</th>
              <th className="border px-2 py-1 text-left">Code</th>
              <th className="border px-2 py-1 text-left">Description</th>
              <th className="border px-2 py-1 text-left">Cat</th>
              <th className="border px-2 py-1 text-left">Area</th>
              <th className="border px-2 py-1 text-right">Qty</th>
              <th className="border px-2 py-1 text-left">Unit</th>
              <th className="border px-2 py-1 text-right">Unit Price</th>
              <th className="border px-2 py-1 text-right">Line Total</th>
            </tr>
          </thead>
          <tbody>
            {lineItems.map((li) => (
              <tr key={li.index}>
                <td className="border px-2 py-1">{li.index}</td>
                <td className="border px-2 py-1">{li.code}</td>
                <td className="border px-2 py-1">{li.description}</td>
                <td className="border px-2 py-1">{li.category}</td>
                <td className="border px-2 py-1">{li.area}</td>
                <td className="border px-2 py-1 text-right">{li.quantity.toFixed(2)}</td>
                <td className="border px-2 py-1">{li.unit}</td>
                <td className="border px-2 py-1 text-right">{li.unitPrice.toFixed(2)}</td>
                <td className="border px-2 py-1 text-right">{li.lineTotal.toFixed(2)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      {/* Totals */}
      <section className="space-y-1 text-sm">
        <h2 className="border-b pb-1 text-lg font-semibold">Financial Summary (Supplement Only)</h2>
        <p>Subtotal: ${subtotal.toFixed(2)}</p>
        <p>
          Tax ({(taxRate * 100).toFixed(2)}%): ${taxAmount.toFixed(2)}
        </p>
        <p>
          O&amp;P:{" "}
          {opEnabled ? `${(opPercent * 100).toFixed(2)}% = $${opAmount.toFixed(2)}` : "Not applied"}
        </p>
        <p className="font-semibold">Total Requested Supplement: ${grandTotal.toFixed(2)}</p>
      </section>

      <footer className="mt-6 border-t pt-4 text-[11px] text-gray-500">
        This supplement packet is intended to document additional items that are required but not
        included in the initial carrier estimate.
      </footer>
    </div>
  );
}
