// lib/intel/automation/executors/claimsPacket.ts
/**
 * 🔥 CLAIMS PACKET EXECUTOR
 * Auto-generates carrier-ready claims packet
 */

import { randomUUID } from "node:crypto";
import { logger } from "@/lib/logger";

import { buildMasterReportPayload } from "@/lib/intel/master/buildMasterPayload";
import { generateClaimsPacket } from "@/lib/intel/reports/claims-packet";
import prisma from "@/lib/prisma";

export async function executeClaimsPacket(claimId: string, orgId: string) {
  logger.debug(`[DOMINUS] Executing Claims Packet for ${claimId}`);

  // Build master payload
  const payload = await buildMasterReportPayload({ claimId, orgId });
  const { claim, property, weatherReports, damageAssessments, supplements } = payload;

  // Generate claims packet
  const packet = await generateClaimsPacket({
    claimId,
    financials: {
      carrierRCV: 0,
      carrierACV: 0,
      contractorRCV: 0,
      underpayment: 0,
      depreciationErrors: [],
      supplementJustification: "See supplement section",
      settlementProjection: { min: 0, max: 0, confidence: 0.85 },
    },
    damage: {
      photoGroups: [],
      locations: [],
      severity: damageAssessments[0]?.primaryPeril || "Unknown",
      materialTypes: [],
      missingItems: [],
      damageNotes: damageAssessments[0]?.summary || "",
    },
    weather: {
      eventTimeline: weatherReports[0]?.globalSummary || "",
      hailSize: weatherReports[0]?.primaryHazard || "",
      windGusts: "",
      eventFrequency: 1,
      verificationMap: "",
      citations: [],
    },
    codeRequirements: {
      ircRequirements: [],
      manufacturerSpecs: [],
      localCodes: [],
      requiredDocumentation: [],
    },
    scope: {
      missingLineItems: [],
      incorrectMeasurements: [],
      requiredUpgrades: [],
      materialCorrections: [],
      laborCorrections: [],
      supplementOpportunities: supplements.map((s) => ({
        description: s.description || "Supplement item",
        priority: "medium",
        value: s.total,
      })),
    },
    property: {
      address: property?.address || "",
      city: property?.city || "",
      state: property?.state || "",
      zip: property?.zip || "",
    },
    claim: {
      claimNumber: claim.claimNumber,
      dateOfLoss: claim.dateOfLoss.toISOString().split("T")[0],
      carrier: claim.carrier || "",
      adjusterName: claim.adjusterName || "",
      policyNumber: claim.policyNumber || "",
    },
  });

  // Save to database
  const report = await prisma.ai_reports.create({
    data: {
      id: randomUUID(),
      orgId,
      claimId,
      type: "claims_packet",
      title: `Claims Packet - ${claim.claimNumber}`,
      prompt: "Auto-generated by Dominus",
      content: JSON.stringify(packet),
      model: "gpt-4o",
      userId: "dominus",
      userName: "Dominus AI",
      status: "generated",
      tokensUsed: 0, // Auto-generated, no AI tokens used
      updatedAt: new Date(),
    },
  });

  logger.debug(`[DOMINUS] Claims Packet Generated - Report ID: ${report.id}`);

  return {
    reportId: report.id,
    packet,
  };
}
