// lib/intel/automation/executors/financial.ts
/**
 * 🔥 FINANCIAL ANALYSIS EXECUTOR
 * Auto-runs financial engine and saves snapshot
 */

import { randomUUID } from "node:crypto";
import { logger } from "@/lib/logger";

import { runAIFinancialAnalysis } from "@/lib/intel/financial/ai";
import { calculateFinancialAnalysis } from "@/lib/intel/financial/engine";
import { buildMasterReportPayload } from "@/lib/intel/master/buildMasterPayload";
import prisma from "@/lib/prisma";

export async function executeFinancialAnalysis(claimId: string, orgId: string) {
  logger.debug(`[DOMINUS] Executing Financial Analysis for ${claimId}`);

  // Build master payload
  const payload = await buildMasterReportPayload({ claimId, orgId });
  const { claim, property, estimates, supplements } = payload;

  // Get carrier/contractor estimates
  const carrierEstimate =
    estimates.find((e) => e.source === "carrier" || e.mode === "insurance") || estimates[0];

  const contractorEstimate =
    estimates.find((e) => e.source === "contractor" || e.mode === "retail") || estimates[0];

  // Run math engine
  const mathResult = calculateFinancialAnalysis({
    carrierEstimate: carrierEstimate ? { rcv: carrierEstimate.grandTotal } : undefined,
    contractorEstimate: contractorEstimate ? { rcv: contractorEstimate.grandTotal } : undefined,
    supplements: supplements.map((s) => ({
      id: s.id,
      total: s.total,
      createdAt: s.createdAt,
    })),
    localTaxRate: 0.089,
    deductible: claim.deductible || 1000,
    pricingZone: property ? `${property.city}-${property.state}` : "UNKNOWN",
  });

  // Run AI analysis
  const aiResult = await runAIFinancialAnalysis({
    carrierEstimate: carrierEstimate ? { rcv: carrierEstimate.grandTotal } : undefined,
    contractorEstimate: contractorEstimate ? { rcv: contractorEstimate.grandTotal } : undefined,
    supplements: supplements.map((s) => ({
      id: s.id,
      total: s.total,
      createdAt: s.createdAt,
    })),
    localTaxRate: 0.089,
    deductible: claim.deductible || 1000,
    pricingZone: property ? `${property.city}-${property.state}` : "UNKNOWN",
    weatherData: "",
    damageAssessment: {},
    damageFindings: [],
    scopeGaps: [],
    codes: [],
    manufacturer: [],
  });

  // Persist result (FinancialSnapshot model is not present in Prisma schema)
  const report = await prisma.ai_reports.create({
    data: {
      id: randomUUID(),
      orgId,
      claimId,
      type: "financial_analysis",
      title: `Financial Analysis - ${claim.claimNumber}`,
      prompt: "Auto-generated by Dominus",
      content: JSON.stringify({ mathResult, aiResult }),
      model: "gpt-4o",
      userId: "dominus",
      userName: "Dominus AI",
      status: "generated",
      tokensUsed: 0,
      updatedAt: new Date(),
    },
  });

  console.log(
    `[DOMINUS] Financial Analysis Complete - Underpayment: $${mathResult.totals.underpayment}`
  );

  return {
    snapshotId: report.id,
    reportId: report.id,
    underpayment: mathResult.totals.underpayment,
    mathResult,
    aiResult,
  };
}
