// lib/intel/automation/executors/tasks.ts
/**
 * 🔥 TASK AUTO-GENERATION SYSTEM
 * Creates priority tasks based on findings
 */

import { getDelegate } from "@/lib/db/modelAliases";
import { logger } from "@/lib/logger";

export async function executeCreateTask(
  claimId: string,
  orgId: string,
  config: {
    title: string;
    description?: string;
    priority: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
    category?: string;
    linkedReportId?: string;
  }
) {
  logger.debug(`[DOMINUS] Creating task: ${config.title}`);

  const task = await getDelegate("automationTask").create({
    data: {
      orgId,
      claimId,
      title: config.title,
      description: config.description || "",
      priority: config.priority,
      category: config.category,
      linkedReportId: config.linkedReportId,
      status: "OPEN",
      autoGenerated: true,
      aiSuggested: true,
    },
  });

  logger.debug(`[DOMINUS] Task created - ID: ${task.id}`);

  return {
    taskId: task.id,
    title: task.title,
  };
}

/**
 * Complete a task
 */
export async function completeTask(taskId: string, orgId: string) {
  await getDelegate("automationTask").update({
    where: { id: taskId, orgId },
    data: {
      status: "COMPLETED",
      completedAt: new Date(),
    },
  });

  return { success: true };
}
