// src/components/report/ReportPreviewLayout.tsx
import clsx from "clsx";

import { GeneratedReport, ReportSection } from "@/lib/report-engine/report-types";

function sectionAccent(section: ReportSection) {
  if (section.importance === "HIGH") return "border-l-4 border-l-red-500";
  if (section.importance === "MEDIUM") return "border-l-4 border-l-amber-400";
  return "border-l-4 border-l-slate-300";
}

function sectionTextStyle(section: ReportSection) {
  switch (section.style) {
    case "technical":
      return "text-xs leading-snug font-mono";
    case "narrative":
      return "text-sm leading-relaxed";
    case "bullet":
      return "text-sm leading-snug";
    case "plain":
    default:
      return "text-sm leading-snug";
  }
}

export function ReportPreviewLayout({ report }: { report: GeneratedReport }) {
  const { title, subtitle, executiveSummary, sections, meta } = report;

  const metaLines: string[] = [];
  if (meta?.claimNumber) metaLines.push(`Claim: ${meta.claimNumber}`);
  if (meta?.dateOfLoss) metaLines.push(`Date of Loss: ${meta.dateOfLoss}`);
  if (meta?.location) metaLines.push(`Location: ${meta.location}`);
  if (meta?.roofType) metaLines.push(`Roof Type: ${meta.roofType}`);
  if (meta?.estimateMode) metaLines.push(`Estimate Mode: ${meta.estimateMode}`);
  if (meta?.totalRequested != null)
    metaLines.push(
      `Total Requested: $${Number(meta.totalRequested).toFixed(2)}`
    );

  return (
    <div className="mx-auto max-w-4xl space-y-6 rounded-xl bg-white p-6 text-black shadow-sm print:border-0 print:p-4 print:shadow-none">
      {/* Header */}
      <header className="space-y-1 border-b pb-3">
        <h1 className="text-xl font-bold">{title || "Untitled Report"}</h1>
        {subtitle && <p className="text-xs text-gray-600">{subtitle}</p>}
        {metaLines.length > 0 && (
          <p className="text-[11px] text-gray-500">
            {metaLines.join(" • ")}
          </p>
        )}
        <p className="text-[10px] text-gray-400">
          Generated by SkaiScraper – {report.reportType} – Audience:{" "}
          {report.audience}
        </p>
      </header>

      {/* Executive Summary */}
      {executiveSummary && (
        <section className="space-y-1">
          <h2 className="border-b pb-1 text-sm font-semibold">
            Executive Summary
          </h2>
          <p className="whitespace-pre-wrap text-sm leading-snug">
            {executiveSummary}
          </p>
        </section>
      )}

      {/* Sections */}
      <div className="space-y-4">
        {sections.map((section) => (
          <section
            key={section.id}
            className={clsx(
              "rounded-lg bg-slate-50 p-3",
              sectionAccent(section)
            )}
          >
            <div className="mb-1 flex items-center justify-between gap-2">
              <h3 className="text-sm font-semibold">{section.title}</h3>
              <span className="text-[10px] uppercase tracking-wide text-gray-500">
                {section.audience} • {section.style}
              </span>
            </div>
            <div className={clsx(sectionTextStyle(section), "whitespace-pre-wrap")}>
              {section.content}
            </div>
          </section>
        ))}
      </div>

      <footer className="mt-3 border-t pt-3 text-[10px] text-gray-500">
        This report is based on the data available at the time of generation. It is
        intended to support, not replace, professional judgment and onsite inspection.
      </footer>
    </div>
  );
}
