import { Text,View } from "@react-pdf/renderer";

import { styles } from "../theme";

export default function Footer({ url }: { url?: string }) {
  return (
    <View style={{ position: "absolute", bottom: 16, left: 28, right: 28 }}>
      <View style={{ ...styles.row, justifyContent: "space-between" }}>
        <Text style={styles.small}>{url ?? "skaiscrape.com"}</Text>
        <Text style={styles.small}>Generated by SkaiScraper</Text>
      </View>
    </View>
  );
}
