import { Image,Text, View } from "@react-pdf/renderer";

import { styles } from "../theme";

export default function Header({
  logo,
  company,
  brandColor,
}: {
  logo?: string;
  company?: string;
  brandColor: string;
}) {
  return (
    <View style={{ ...styles.row, justifyContent: "space-between", marginBottom: 12 }}>
      <View style={{ ...styles.col }}>
        <Text style={{ ...styles.h3, color: brandColor }}>{company ?? "Your Company"}</Text>
        <Text style={styles.small}>Branded report generated by SkaiScraper</Text>
      </View>
      {logo ? <Image src={logo} style={{ width: 64, height: 64, borderRadius: 8 }} /> : null}
    </View>
  );
}
