// components/automation/DominusTaskBoard.tsx
/**
 * 🔥 TASK MANAGER KANBAN BOARD
 * Priority-based task management
 */

"use client";

import { CheckCircle2 } from "lucide-react";

import { Button } from "@/components/ui/button";

interface Task {
  id: string;
  title: string;
  description: string | null;
  priority: string;
  status: string;
  category: string | null;
  autoGenerated: boolean;
  createdAt: Date;
}

interface DominusTaskBoardProps {
  tasks: Task[];
  onComplete: (taskId: string) => void;
}

export function DominusTaskBoard({ tasks, onComplete }: DominusTaskBoardProps) {
  const tasksByPriority = {
    CRITICAL: tasks.filter((t) => t.priority === "CRITICAL" && t.status === "OPEN"),
    HIGH: tasks.filter((t) => t.priority === "HIGH" && t.status === "OPEN"),
    MEDIUM: tasks.filter((t) => t.priority === "MEDIUM" && t.status === "OPEN"),
    LOW: tasks.filter((t) => t.priority === "LOW" && t.status === "OPEN"),
  };

  const getPriorityStyles = (priority: string) => {
    switch (priority) {
      case "CRITICAL":
        return "bg-red-100 border-red-300 text-red-900";
      case "HIGH":
        return "bg-orange-100 border-orange-300 text-orange-900";
      case "MEDIUM":
        return "bg-yellow-100 border-yellow-300 text-yellow-900";
      case "LOW":
        return "bg-green-100 border-green-300 text-green-900";
      default:
        return "bg-gray-100 border-gray-300 text-gray-900";
    }
  };

  const getPriorityIcon = (priority: string) => {
    switch (priority) {
      case "CRITICAL":
        return "🟥";
      case "HIGH":
        return "🟧";
      case "MEDIUM":
        return "🟨";
      case "LOW":
        return "🟩";
      default:
        return "⬜";
    }
  };

  const renderTaskColumn = (priority: string, tasks: Task[]) => (
    <div className="min-w-[250px] flex-1">
      <div className={`rounded-t-lg border p-3 ${getPriorityStyles(priority)}`}>
        <h3 className="flex items-center gap-2 font-bold">
          {getPriorityIcon(priority)} {priority} ({tasks.length})
        </h3>
      </div>
      <div className="space-y-2 rounded-b-lg border border-t-0 bg-gray-50 p-2">
        {tasks.length === 0 ? (
          <p className="py-4 text-center text-sm text-gray-500">No tasks</p>
        ) : (
          tasks.map((task) => (
            <div
              key={task.id}
              className="rounded-lg border bg-white p-3 shadow-sm transition-shadow hover:shadow-md"
            >
              <h4 className="text-sm font-semibold">{task.title}</h4>
              {task.description && (
                <p className="mt-1 text-xs text-gray-600">{task.description}</p>
              )}
              {task.category && (
                <span className="mt-2 inline-block rounded bg-gray-100 px-2 py-1 text-xs">
                  {task.category}
                </span>
              )}
              {task.autoGenerated && (
                <span className="ml-2 mt-2 inline-block rounded bg-purple-100 px-2 py-1 text-xs text-purple-900">
                  🤖 Auto-generated
                </span>
              )}
              <Button
                size="sm"
                variant="outline"
                onClick={() => onComplete(task.id)}
                className="mt-3 w-full"
              >
                <CheckCircle2 className="mr-2 h-4 w-4" />
                Complete
              </Button>
            </div>
          ))
        )}
      </div>
    </div>
  );

  return (
    <div className="flex gap-4 overflow-x-auto pb-4">
      {renderTaskColumn("CRITICAL", tasksByPriority.CRITICAL)}
      {renderTaskColumn("HIGH", tasksByPriority.HIGH)}
      {renderTaskColumn("MEDIUM", tasksByPriority.MEDIUM)}
      {renderTaskColumn("LOW", tasksByPriority.LOW)}
    </div>
  );
}
