// src/app/(app)/exports/reports/[reportId]/adjuster/page.tsx
import { auth } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";

import { buildReportAdjusterPayload } from "@/lib/export/payloads";

type PageProps = { params: { reportId: string } };

export default async function AdjusterPacketPage({ params }: PageProps) {
  const { userId, orgId } = await auth();
  if (!userId) redirect("/sign-in");

  const reportId = params.reportId;

  const payload = await buildReportAdjusterPayload(reportId, orgId ?? null);

  const { claim, report, damageAssessments, weatherReports, estimates, supplements, scopes } =
    payload;

  return (
    <div className="mx-auto max-w-5xl space-y-6 bg-white p-8 text-black print:p-4">
      {/* Header */}
      <header className="space-y-1 border-b pb-4">
        <h1 className="text-2xl font-bold">{report.title || "Adjuster Claim Packet"}</h1>
        <p className="text-sm">
          Claim: <strong>{claim.claimNumber ?? claim.id?.slice(0, 8) ?? "Unknown"}</strong>
        </p>
        <p className="text-xs text-gray-600">Generated by SkaiScraper – Adjuster-ready packet</p>
      </header>

      {/* Claim Info */}
      <section className="space-y-1 text-sm">
        <h2 className="border-b pb-1 text-lg font-semibold">Claim Information</h2>
        <p>Insured: {claim.insured_name ?? "—"}</p>
        <p>Property: {claim.propertyAddress ?? claim.properties?.address ?? "—"}</p>
        <p>Carrier: {claim.carrierName ?? "—"}</p>
        <p>
          Date of Loss: {claim.dateOfLoss ? new Date(claim.dateOfLoss).toLocaleDateString() : "—"}
        </p>
        <p>Loss Type: {claim.lossType ?? "—"}</p>
      </section>

      {/* Report Summary */}
      <section className="space-y-2 text-sm">
        <h2 className="border-b pb-1 text-lg font-semibold">Executive Summary</h2>
        <p className="whitespace-pre-wrap">
          {report.data?.summary ??
            "This packet summarizes the inspection findings, weather verification, and requested line items associated with this claim."}
        </p>
      </section>

      {/* Damage Section */}
      {damageAssessments.length > 0 && (
        <section className="space-y-2 text-sm">
          <h2 className="border-b pb-1 text-lg font-semibold">Damage Assessment</h2>
          <p>Most recent assessment: {new Date(damageAssessments[0].createdAt).toLocaleString()}</p>
          <p className="whitespace-pre-wrap">
            {damageAssessments[0].summary ?? "No summary provided."}
          </p>
        </section>
      )}

      {/* Weather Section */}
      {weatherReports.length > 0 && (
        <section className="space-y-2 text-sm">
          <h2 className="border-b pb-1 text-lg font-semibold">Weather Verification</h2>
          <p>
            Peril: {weatherReports[0].peril ?? "—"} | DOL:{" "}
            {weatherReports[0].dol ? new Date(weatherReports[0].dol).toLocaleDateString() : "—"}
          </p>
          <p className="whitespace-pre-wrap">
            {weatherReports[0].data?.summary ??
              "Weather data confirms relevant storm activity near this location and Date of Loss."}
          </p>
        </section>
      )}

      {/* Scope Section */}
      {scopes.length > 0 && (
        <section className="space-y-2 text-sm">
          <h2 className="border-b pb-1 text-lg font-semibold">Scope of Work (Summary)</h2>
          <p className="whitespace-pre-wrap">
            {scopes[0].summary ?? "Scope of work generated for this claim."}
          </p>
        </section>
      )}

      {/* Estimates Section */}
      {estimates.length > 0 && (
        <section className="space-y-2 text-sm">
          <h2 className="border-b pb-1 text-lg font-semibold">Estimate Overview</h2>
          <p>
            Latest estimate: {estimates[0].title ?? `Estimate ${estimates[0].id.slice(0, 8)}`} (
            {estimates[0].mode ?? "—"})
          </p>
          <p className="text-xs text-gray-600">
            For full line item detail, reference the attached estimate export.
          </p>
        </section>
      )}

      {/* Supplements Section */}
      {supplements.length > 0 && (
        <section className="space-y-2 text-sm">
          <h2 className="border-b pb-1 text-lg font-semibold">Supplement Request</h2>
          <p className="whitespace-pre-wrap">
            {supplements[0].notesToAdjuster ??
              "We are requesting the following additional items to bring the scope in line with code and manufacturer requirements."}
          </p>
        </section>
      )}

      {/* Footer */}
      <footer className="mt-6 border-t pt-4 text-[11px] text-gray-500">
        Prepared by SkaiScraper – generated packet for claim handling.
      </footer>
    </div>
  );
}
