"use client";

export function ClaimActivityFeed({ claim_id: claimId }: { claim_id: string }) {
  const activities = [
    { time: "2 hours ago", text: "Supplement proposal generated by AI" },
    { time: "1 day ago", text: "Photos uploaded for inspection" },
  ];

  return (
    <ul className="space-y-2">
      {activities.map((a, i) => (
        <li key={i} className="text-sm">
          <span className="font-medium text-[color:var(--primary)]">{a.time}</span>
          {" – "}
          <span className="text-[color:var(--muted)]">{a.text}</span>
        </li>
      ))}
    </ul>
  );
}
