// src/lib/report-engine/email.ts
import { GeneratedReport } from "./report-types";

type EmailPayload = {
  subject: string;
  html: string;
  text: string;
};

type ReportContext = {
  claimNumber?: string | null;
  insured_name?: string | null;
  propertyAddress?: string | null;
  carrierName?: string | null;
};

function firstParagraphOrSummary(report: GeneratedReport): string {
  if (report.executiveSummary) return report.executiveSummary;

  const first = report.sections?.[0]?.content ?? "";
  return first.length > 600 ? first.slice(0, 600) + "..." : first;
}

export function buildAdjusterEmailFromReport(
  report: GeneratedReport,
  ctx: ReportContext
): EmailPayload {
  const claimLabel = ctx.claimNumber || report.meta?.claimNumber || "this claim";
  const insured = ctx.insured_name || "the insured";
  const property = ctx.propertyAddress || report.meta?.location || "the property";

  const subject = `Claims Report – Claim ${claimLabel}`;

  const intro = `
Dear Adjuster,

Please find attached a detailed report summarizing the observed damages, recommended scope of repairs, and supporting documentation for ${claimLabel} (${insured}, ${property}).
  `.trim();

  const summary = firstParagraphOrSummary(report);

  const closing = `
If you have any questions or require additional documentation (photos, invoices, or code references), please let us know. We look forward to working with you toward a fair and accurate resolution.

Sincerely,
Your Restoration Team
  `.trim();

  const text = [intro, "", "Summary:", summary, "", closing].join("\n\n");

  const html = `
<p>${intro}</p>

<h3>Summary</h3>
<p style="white-space: pre-wrap; font-size: 13px; line-height: 1.5;">
${summary.replace(/\n/g, "<br />")}
</p>

<hr style="margin: 16px 0;" />

<p style="font-size: 12px; color: #555;">
This email was generated by SkaiScraper's Intelligence Core based on the current claim file, damage assessments, and documentation.
</p>

<p>${closing.replace(/\n/g, "<br />")}</p>
  `.trim();

  return { subject, html, text };
}

export function buildHomeownerEmailFromReport(
  report: GeneratedReport,
  ctx: ReportContext
): EmailPayload {
  const claimLabel = ctx.claimNumber || report.meta?.claimNumber || "your claim";
  const insured = ctx.insured_name || "you";
  const property = ctx.propertyAddress || report.meta?.location || "your property";

  const subject = `Your Project Summary – ${property}`;

  const intro = `
Hi ${insured},

We've put together a clear summary of your roof/project at ${property}. This report explains what we found, what we recommend, and what to expect next.
  `.trim();

  const summary = firstParagraphOrSummary(report);

  const closing = `
If anything is unclear or you'd like us to walk you through the details, reply to this email or give us a call. We're here to make this process as simple and stress-free as possible.

Thank you for trusting us with ${property}.
  `.trim();

  const text = [intro, "", "Summary:", summary, "", closing].join("\n\n");

  const html = `
<p>${intro}</p>

<h3>Summary</h3>
<p style="white-space: pre-wrap; font-size: 13px; line-height: 1.5;">
${summary.replace(/\n/g, "<br />")}
</p>

<hr style="margin: 16px 0;" />

<p style="font-size: 12px; color: #555;">
This overview is based on the current inspection details, photos, and project notes in our system.
</p>

<p>${closing.replace(/\n/g, "<br />")}</p>
  `.trim();

  return { subject, html, text };
}
