"use client";

import { useEffect, useState } from "react";

export default function WeatherSharePage({ params }: any) {
  const { token } = params;
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch(`/api/weather/share/${token}`)
      .then((res) => {
        if (!res.ok) throw new Error("Report not found");
        return res.json();
      })
      .then((json) => {
        setReport(json.report);
        setLoading(false);
      })
      .catch((err) => {
        setError(err.message);
        setLoading(false);
      });
  }, [token]);

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <div className="text-center">
          <div className="mx-auto mb-4 h-12 w-12 animate-spin rounded-full border-b-2 border-blue-600"></div>
          <p className="text-gray-600">Loading weather intelligence…</p>
        </div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <div className="text-center">
          <h1 className="mb-4 text-3xl font-bold text-red-600">Report Not Found</h1>
          <p className="text-gray-600">This weather intelligence report is not available.</p>
        </div>
      </div>
    );
  }

  const packet = report.providerRaw || report.payload;

  return (
    <div className="min-h-screen bg-slate-950">
      <div className="bg-gradient-blue py-8 text-white">
        <div className="mx-auto max-w-4xl px-6">
          <h1 className="mb-2 text-4xl font-bold">Weather Intelligence Report</h1>
          <p className="text-blue-100">Powered by SkaiScraper</p>
        </div>
      </div>

      <div className="mx-auto max-w-4xl space-y-8 px-6 py-10">
        <section className="rounded-lg border border-slate-800 bg-slate-900 p-6 shadow-lg">
          <h2 className="mb-4 text-2xl font-semibold text-slate-100">Storm Summary</h2>
          <p className="leading-relaxed text-slate-300">{packet.stormSummary}</p>
        </section>

        <div className="grid gap-6 md:grid-cols-2">
          <section className="rounded-lg border border-slate-800 bg-slate-900 p-6 shadow-lg">
            <h2 className="mb-2 text-xl font-semibold text-slate-100">Hazard Level</h2>
            <div className="text-3xl font-bold text-orange-400">{packet.hazardLevel}</div>
          </section>

          <section className="rounded-lg border border-slate-800 bg-slate-900 p-6 shadow-lg">
            <h2 className="mb-2 text-xl font-semibold text-slate-100">Severity Score</h2>
            <div className="text-3xl font-bold text-red-400">{packet.severityScore}/10</div>
          </section>
        </div>

        {packet.hail && <DataSection title="🧊 Hail Analysis" data={packet.hail} />}

        {packet.wind && <DataSection title="🌬️ Wind Analysis" data={packet.wind} />}

        {packet.rain && <DataSection title="🌧️ Rainfall Data" data={packet.rain} />}

        {packet.radar && <DataSection title="📡 Radar Intelligence" data={packet.radar} />}

        {packet.iceSnow && <DataSection title="❄️ Ice & Snow Data" data={packet.iceSnow} />}

        <section className="rounded-lg border border-slate-800 bg-slate-900 p-6 shadow-lg">
          <h2 className="mb-4 text-2xl font-semibold text-slate-100">🕒 Timeline</h2>
          <p className="whitespace-pre-wrap leading-relaxed text-slate-300">{packet.timeline}</p>
        </section>

        <section className="rounded-lg border-l-4 border-blue-500 bg-blue-950 p-6">
          <h2 className="mb-4 text-2xl font-semibold text-slate-100">✅ Conclusions</h2>
          <p className="leading-relaxed text-slate-300">{packet.conclusions}</p>
        </section>

        <div className="rounded-lg border border-slate-800 bg-slate-900/50 p-6 text-center text-sm text-slate-400">
          <p>This meteorological intelligence report was generated by SkaiScraper AI.</p>
          <p className="mt-2">
            For more information, visit{" "}
            <a href="https://skaiscrape.com" className="text-blue-400 hover:underline">
              skaiscrape.com
            </a>
          </p>
        </div>
      </div>
    </div>
  );
}

function DataSection({ title, data }: any) {
  if (!data || Object.keys(data).length === 0) return null;

  return (
    <section className="rounded-lg border border-slate-800 bg-slate-900 p-6 shadow-lg">
      <h2 className="mb-4 text-2xl font-semibold text-slate-100">{title}</h2>
      <div className="space-y-2">
        {Object.entries(data).map(
          ([key, value]: any) =>
            value && (
              <div key={key} className="flex justify-between border-b border-slate-700 pb-2">
                <span className="font-medium capitalize text-slate-400">
                  {key.replace(/([A-Z])/g, " $1").trim()}:
                </span>
                <span className="text-slate-100">{value}</span>
              </div>
            )
        )}
      </div>
    </section>
  );
}
