// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

import type { Database } from "./types";

// Use Next.js environment variable names so this client works when running under Next.
const SUPABASE_URL =
  (process.env.NEXT_PUBLIC_SUPABASE_URL as string | undefined) ||
  process.env?.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  (process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY as string | undefined) ||
  process.env?.VITE_SUPABASE_PUBLISHABLE_KEY;

function missingSupabaseProxy(msg: string) {
  const handler: ProxyHandler<any> = {
    get(_target, prop) {
      throw new Error(`${msg} — attempted to access supabase.${String(prop)}`);
    },
    apply() {
      throw new Error(msg);
    },
  };
  return new Proxy({}, handler) as unknown as ReturnType<typeof createClient>;
}

function createSupabaseClient() {
  // Validate URL quickly — avoid calling createClient with an invalid/missing URL which
  // causes runtime errors during Next prerender (build-time).
  if (
    !SUPABASE_URL ||
    typeof SUPABASE_URL !== "string" ||
    !/^https?:\/\//i.test(SUPABASE_URL) ||
    SUPABASE_URL.includes("<") ||
    SUPABASE_URL.includes(">") ||
    SUPABASE_URL.includes("<project>")
  ) {
    return missingSupabaseProxy(
      "Supabase not configured: NEXT_PUBLIC_SUPABASE_URL is missing or malformed. Please set a valid NEXT_PUBLIC_SUPABASE_URL in your environment before using Supabase features."
    );
  }

  try {
    const options: any = {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
      },
    } as const;

    // localStorage is only available in the browser. Only set storage when running client-side.
    if (typeof window !== "undefined" && typeof localStorage !== "undefined") {
      options.auth.storage = localStorage;
    }

    // Validate publishable key as well — an empty or placeholder key will likely
    // cause runtime errors when the client is used.
    if (
      !SUPABASE_PUBLISHABLE_KEY ||
      SUPABASE_PUBLISHABLE_KEY.includes("<") ||
      SUPABASE_PUBLISHABLE_KEY.includes(">")
    ) {
      return missingSupabaseProxy(
        "Supabase publishable key (NEXT_PUBLIC_SUPABASE_ANON_KEY) is missing or malformed."
      );
    }

    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY || "", options);
  } catch (err) {
    return missingSupabaseProxy(`Failed to initialize Supabase client: ${String(err)}`);
  }
}

// Export a lazily-created client (created at import time but guarded). Callsites that
// attempt to use Supabase without proper env vars will receive a clear error instead
// of crashing the Next build during prerender.
export const supabase = createSupabaseClient();
